name       : python-flit
version    : 3.7.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/f/flit/flit-3.7.1.tar.gz : 3c9bd9c140515bfe62dd938c6610d10d6efb9e35cc647fc614fe5fb3a5036682
homepage   : https://github.com/pypa/flit
license    : BSD-3-Clause
summary    : Simplified packaging of Python modules
description: |
    Flit is a simple way to put Python packages and modules on PyPI. It tries to require less thought about packaging and help you avoid common mistakes.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-docutils
    - python-flit-core
    - python-requests
    - python-tomli
    - python-tomli-w
build      : |
    %python3_setup
install    : |
    %python3_install
